# Generated by Django 5.1.11 on 2025-08-31 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_author_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='users/avatars/', verbose_name='Аватар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='users.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
